### ISSUE TITLE
A non logged in user accessing the "/mailbox/trash" URL receives a 500 error

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#114]
While testing the mailbox functionality out, I noticed that if a user is not logged in and goes to the "/mailbox/trash" URL, the following error message appears in the Rails logs:

````
1436 2015-08-23T11:04:20.600691+00:00 heroku[router]: at=info method=GET path="/mailbox/trash" host=ebwiki.org request_id=024cf955-d680-4347-8fbc-f73ac288db2
   1437 2015-08-23T11:04:20.584473+00:00 app[web.1]:
   1438 2015-08-23T11:04:20.584478+00:00 app[web.1]: NoMethodError (undefined method `mailbox' for nil:NilClass):
   1439 2015-08-23T11:04:20.584480+00:00 app[web.1]:   app/controllers/application_controller.rb:23:in `mailbox'
   1440 2015-08-23T11:04:20.584482+00:00 app[web.1]:   app/controllers/mailbox_controller.rb:13:in `trash'
   1441 2015-08-23T11:04:20.584483+00:00 app[web.1]:
   1442 2015-08-23T11:04:20.584484+00:00 app[web.1]:
   1443 2015-08-23T11:04:24.853520+00:00 app[web.1]:
````

and the user receives the following error page:

<img width="1280" alt="screenshot 2015-08-23 07 07 05" src="https://cloud.githubusercontent.com/assets/13509/9427969/e6ec9fd8-4965-11e5-9e32-e499e33cda5b.png">

If the user is not logged in, they should be redirected to the login page

**Comment by trystant** [comment]
This has been resolved by the fix for #115
