### ISSUE TITLE
A link to the "/mailbox" URL results in a 404 error

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#115]
If a user goes to "http://ebwiki.org/mailbox", the user sees this page:
<img width="1280" alt="screenshot 2015-08-23 07 06 59" src="https://cloud.githubusercontent.com/assets/13509/9427977/8792794e-4966-11e5-87b6-306968b9c4fe.png">

 error appears in the logs:

````
1444 2015-08-23T11:04:24.853526+00:00 app[web.1]: ActionController::RoutingError (No route matches [GET] "/mailbox"):
   1445 2015-08-23T11:04:24.853528+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `
   1446 2015-08-23T11:04:24.853530+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_w
   1447 2015-08-23T11:04:24.853531+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `c
   1448 2015-08-23T11:04:24.853533+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
   1449 2015-08-23T11:04:24.853534+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
   1450 2015-08-23T11:04:24.853536+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in ta
   1451 2015-08-23T11:04:24.853538+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
   1452 2015-08-23T11:04:24.853539+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
   1453 2015-08-23T11:04:24.853540+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
   1454 2015-08-23T11:04:24.853542+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/ahoy_matey-1.1.1/lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
   1455 2015-08-23T11:04:24.853543+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
 1456 2015-08-23T11:04:24.853545+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
   1457 2015-08-23T11:04:24.853548+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
   1458 2015-08-23T11:04:24.853549+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
   1459 2015-08-23T11:04:24.853551+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middlewar
   1460 2015-08-23T11:04:24.853552+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
   1461 2015-08-23T11:04:24.853558+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
   1462 2015-08-23T11:04:24.853559+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
   1463 2015-08-23T11:04:24.853561+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/configuration.rb:51:in `call'
   1464 2015-08-23T11:04:24.853562+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
   1465 2015-08-23T11:04:24.853564+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
   1466 2015-08-23T11:04:24.853565+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
   1467 2015-08-23T11:04:24.853554+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/heroku_rails_deflate-1.0.3/lib/heroku_rails_deflate/serve_zipped_assets.rb:
   1468 2015-08-23T11:04:24.853567+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
   1469 2015-08-23T11:04:24.853555+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/deflater.rb:35:in `call'
   1470 2015-08-23T11:04:24.853569+00:00 app[web.1]:
   1471 2015-08-23T11:04:24.853556+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
   1472 2015-08-23T11:04:24.853570+00:00 app[web.1]:
   1473 2015-08-23T11:04:24.853566+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
````

If the user is not logged in, they should be redirected to the login page.
If the user is logged in, they should be redirected to the mailbox inbox, or "http://ebwiki.org/mailbox/inbox"

**Comment by campgurus** [comment]
how does the user get to /mailbox? did they type the url manually? Trying to replicate.

**Comment by trystant** [comment]
Yes, by typing it manually. We have to account for users doing that, copy & pasting as well as hackers who won't type, but just enter common URLs...like "/mailbox".

**Comment by campgurus** [comment]
@trystant  what is the desired outcome in these instances where a user manually types in and attempts to visit a nonexistent url? Do we just want to design a better error page for all 404 responses?

**Comment by campgurus** [comment]
Graceful ways of handling 404 errors

https://gorails.com/forum/error-handling-in-ruby-4

**Comment by campgurus** [comment]
@trystant how do you want to handle these errors?

**Comment by trystant** [comment]
I think that the /mailbox url should go to the User's mailbox, which is
also known as /mailbox/inbox.

That would meet up with a user expectation more than a 404 error.


On Sun, Sep 20, 2015 at 7:34 AM, campgurus <notifications@github.com> wrote:

> @trystant <https://github.com/trystant> how do you want to handle these
> errors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/115#issuecomment-141779087>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by campgurus** [comment]
If a user types `http://ebwiki.org/mailbox`, how does the app know which user mailbox to go to?

**Comment by trystant** [comment]
If a user is logged in, they should go to their mailbox.

If a user is not logged in, they should be asked to log in.

**Comment by campgurus** [comment]
Is this a matter of making adjustments to routes.rb?

**Comment by trystant** [comment]
This is now fixed.
