### ISSUE TITLE
Mailchimp subscription status not properly reflected in User Profile page

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#117]
If a user has chosen to subscribe to the newsletter, their subscription status isn't reflected on the profile page. I am a subscriber member, but that status isn't reflected in my profile.

Specifically, the mailchimp newsletter should only go out to people who have chosen to subscribe to the newsletter. The code should also UNSUBSCRIBE the user if they choose not to subscribe anymore. 

The `add_to_mailchimp` method in User needs a corresponding `remove_from_mailchimp` method at the least, and both of them should have specs in `spec/models/user_spec.rb` to verify their behavior.

In addition, Mailchimp has some guidelines for syncing list data between us and them. Read:
* [Syncing database changes from Mailchimp to you](https://apidocs.mailchimp.com/api/how-to/sync-mailchimp-to-you.php?_ga=1.60769325.1802287707.1436113515)
* [Syncing database changes from you to Mailchimp](https://apidocs.mailchimp.com/api/how-to/sync-you-to-mailchimp.php?_ga=1.32810430.1802287707.1436113515)

We need to determine the best way to keep these lists in sync

**Comment by campgurus** [comment]
Adding this link to SO conversation on this issue: http://stackoverflow.com/questions/32356804/checking-user-subscription-status-on-a-mailchimp-list-in-rails-4?noredirect=1#comment52649316_32356804

Pertinent comment on optimizing API calls:

```Ok I was able to parse this array. It turns out that gb.lists(ENV['MAILCHIMP_LIST_ID']).members.retrieve returns a hash of 4 arrays. one of these arrays is the "members" array which includes a hash for each person on the list or pending. so gb.lists(ENV['MAILCHIMP_LIST_ID']).members.retrieve["members"] returns an array of hashes. from there, I can access a particular user has from the email address with gb.lists(ENV['MAILCHIMP_LIST_ID']).members.retrieve["members"].find{|h| h['email_address'] == "#{self.email}"} – user2799827 yesterday

One note: this is a pretty awful way of doing this. You're essentially retrieving an entire list. I think you can do something like this: gb.lists(ENV['MAILCHIMP_LIST_ID']).members(Digest::MD5.new('test9@gmail.com'.do‌​wncase)) – TooMuchPete 11 hours ago ```

**Comment by campgurus** [comment]
Here is an issue: 

If a user signs up via the mail chimp link on our front page, the user is not registered as "pending" on MailChimp. So if a user visits their edit profile page, they still see an empty checkbox and a message to check the box to sign up.

If they check the box and hit update, they get an error because we see that the email is not in MC so we attempt to create it.  A 400 error returns because the email address is already on MailChimp.

stack trace and error:

Gibbon::MailChimpError in UsersController#update
the server responded with status 400

.bundle/gems/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:100:in `handle_error'
.bundle/gems/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:16:in `rescue in post'
.bundle/gems/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/api_request.rb:10:in `post'
.bundle/gems/ruby/2.2.0/gems/gibbon-2.0.0/lib/gibbon/request.rb:28:in `create'
app/models/user.rb:60:in `add_to_mailchimp'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:237:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:237:in `block in halting'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `block in call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `each'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
.bundle/gems/ruby/2.2.0/gems/activemodel-4.2.3/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
.bundle/gems/ruby/2.2.0/gems/activemodel-4.2.3/lib/active_model/validations.rb:334:in `valid?'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:58:in `valid?'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:83:in `perform_validations'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:37:in `save'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:21:in `save'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block in save'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:285:in `save'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/persistence.rb:252:in `block in update'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/persistence.rb:250:in `update'
app/controllers/users_controller.rb:20:in `update'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
.bundle/gems/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/logging.rb:107:in `process_action'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
.bundle/gems/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
.bundle/gems/ruby/2.2.0/gems/bullet-4.14.7/lib/bullet/rack.rb:12:in `call'
.bundle/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
.bundle/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
.bundle/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
.bundle/gems/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:377:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/reloader.rb:73:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
.bundle/gems/ruby/2.2.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
.bundle/gems/ruby/2.2.0/gems/rollbar-1.5.3/lib/rollbar.rb:799:in `scoped'
.bundle/gems/ruby/2.2.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
.bundle/gems/ruby/2.2.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
.bundle/gems/ruby/2.2.0/gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
.bundle/gems/ruby/2.2.0/gems/ahoy_matey-1.1.1/lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
.bundle/gems/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by campgurus** [comment]
MailChimp support looked at our call and offered the following suggestion:

Thanks for writing back in. After checking out the calls that are being made to check for the subscribers on the list, it looks like a GET request to the List Members Collection is being made. However, without any pagination in the request, it'll just return the 10 most recent folks added to the list. Because there are more than 10 total members across the different portions on the list, this is likely why you're not seeing everyone.

Instead, I would recommend checking for the subscribers independently on the list. To this, you'd make a GET request to the List Member Instance. The endpoint for that URL is `lists/<<listID>>/members/<<SubscriberID>> :` http://kb.mailchimp.com/api/resources/lists/members/lists-members-instance

Otherwise, if you'd still like to get the subscribers that are pending all at once, you can paginate by adding "count" and "offset" parameters as query strings at the end of the endpoint URL. For example,  `lists/<<listID>>/members?count=100&offset=0` would get the first 100 list members and `lists/<<listID>>/members?count=100&offset=100` would get 101-200.

Alternatively, you can get just the pending subscribers by filtering by their status. This is also done by adding a query string to the end of the endpoint URL, like this:

`lists/<<listID>>/members?status=pending`

Because it looks like you're using a wrapper, you may need to make changes to the library to allow you to edit the query strings at the end of the URL you're using to make the requests.

**Comment by campgurus** [comment]
last exchange:

One last question.  The only information I have about the user is their email address.  The endpoint: 

```lists/<<listID>>/members/<<SubscriberID>>```

looks like I can retrieve a specific user if i have their subscriber id.  However, I am trying to determine if a user has a MailChimp status based on their email address. Is this the right endpoint for that?

from MC Support:

Yep, that would be the correct endpoint if you'd like to look up a member status by email address. the Subscriber ID in this case is the md5 hash of their email address. If you calculate the md5 hash and add it to the endpoint, a GET request to that endpoint will retrieve the subscriber information for the list if they're on there. This will include their status as well.

**Comment by campgurus** [comment]
Ok we are close.

Subscribers are identified by the MD5 hash of the lowercase version of their email address so you can easily predict the API URL of a subscriber's data.

For example, to get the MD5 hash of the email address Urist.McVankab@freddiesjokes.com, first convert the address to its lowercase version: urist.mcvankab@freddiesjokes.com. The MD5 hash of urist.mcvankab@freddiesjokes.com is 62eeb292278cc15f5817cb78f7790b08

so to return the member object in our case, this will work:

``` gb.lists(ENV['MAILCHIMP_LIST_ID']).members(Digest::MD5.hexdigest("#{self.email}")) ```

So with that in place, a user who subscribes by any means has a status of "pending" which is great. H/e if a user creates a new account, and has not signed up for MailChimp previously, MC returns a 404 error, which we are not handling well.

**Comment by campgurus** [comment]
This is fixed issue is included in #116

**Comment by campgurus** [comment]
this solution seems to have disappeared from the master branch. reopening and assigning to @trystant to take a quick look.  In the meantime i will try to locate the branch where we had the working solution.
