### ISSUE TITLE
Elasticsearch not working on Travis

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#297]
On the current Travis [build][https://travis-ci.org/BOWiki/BOW/builds/102651842], there are missing indexes:

```
1) ArticlesController#index assigns all articles to @articles
     Failure/Error: let(:articles) { FactoryGirl.create_list(:article, 4) }
     Elasticsearch::Transport::Transport::Errors::NotFound:
       [404] {"error":"IndexMissingException[[articles_test] missing]","status":404}
     # ./spec/controllers/articles_controller_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/controllers/articles_controller_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:67:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:66:in `block (2 levels) in <top (required)>'
```

**Comment by trystant** [comment]
This was fixed by removing a link to the external elasticsearch provider and rebuilding the indexes.
