### ISSUE TITLE
Add rspec to test send_followers email

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#454]
We want to test to confirm that the subject of the email contains the title of the case.  The code works fine, so we are just adding a quick (right...) rspec to automate testing of the feature. 

I have hit a sticking point though and cannot yet get the test to work.  Here is the latest code:
```   
describe 'followers_email' do
    let(:user) { mock_model User, name: 'John', email: 'john@email.com', all_following: [Article.new]}
    let(:user_two) { mock_model User, name: 'Brown', email: 'brown@email.com', all_following: [Article.new]}
    let(:article) {mock_model Article, title: 'John Smith', content: 'some content', state_id: 33}
    users = [:user, :user_two]
    let(:mail) { UserNotifier.send_followers_email(users, article) }

    it 'renders the subject' do
      expect(mail.subject).to eql('The John Smith case has been updated on EBWiki.')
    end

    it 'renders the receiver email' do
      expect(mail.to).to eql([user.email])
    end

    it 'renders the sender email' do
      expect(mail.from).to eql(['EndBiasWiki@gmail.com'])
    end
  end
```

and the resulting error trace:

```
1) UserNotifier followers_email renders the subject
     Failure/Error: mail( :to => user.email, :subject => "The #{@article.title} case has been updated on EBWiki." )
     
     NoMethodError:
       undefined method `email' for :user:Symbol
     # ./app/mailers/user_notifier.rb:14:in `block in send_followers_email'
     # ./app/mailers/user_notifier.rb:13:in `each'
     # ./app/mailers/user_notifier.rb:13:in `send_followers_email'
     # ./.bundle/gems/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
     # ./.bundle/gems/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # ./.bundle/gems/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
     # ./.bundle/gems/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # ./.bundle/gems/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # ./.bundle/gems/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # ./.bundle/gems/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
     # ./.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
     # ./.bundle/gems/ruby/2.3.0/gems/actionmailer-4.2.6/lib/action_mailer/base.rb:596:in `block in process'
     # ./.bundle/gems/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
     # ./.bundle/gems/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/gems/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
     # ./.bundle/gems/ruby/2.3.0/gems/actionmailer-4.2.6/lib/action_mailer/base.rb:593:in `process'
     # ./.bundle/gems/ruby/2.3.0/gems/actionmailer-4.2.6/lib/action_mailer/base.rb:584:in `initialize'
     # ./.bundle/gems/ruby/2.3.0/gems/actionmailer-4.2.6/lib/action_mailer/message_delivery.rb:25:in `new'
     # ./.bundle/gems/ruby/2.3.0/gems/actionmailer-4.2.6/lib/action_mailer/message_delivery.rb:25:in `__getobj__'
     # ./spec/mailers/user_notifier_spec.rb:55:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:67:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:66:in `block (2 levels) in <top (required)>'
```

**Comment by campgurus** [comment]
We have a passing spec for this now,as I am looking at the code.
