### ISSUE TITLE
Article slug not updating when @article is updated

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#511]
It should work and I thought we had tested this, but apparently it is not working.  I think the test saves the slug as nil before updating, whereas this is not happening outside of the test, which sets slug: nil without actually saving it.

**Comment by campgurus** [comment]
making these changes causes the correct behavior but also causes a prior spec to fail.  There is not h/e the normal clear error message. trace below:

```Failures:

  1) ArticlesController#show when requested article exists success
     Failure/Error: expect(response).to be_success
       expected `#<ActionController::TestResponse:0x007f8ecf87f590 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007f8eca5a38d0>, @stream=#<ActionDispatch::Response::Buffer:0x007f8ed3adb7e0 @response=#<ActionController::TestResponse:0x007f8ecf87f590 ...>, @buf=["<html><body>You are being <a href=\"http://test.host/articles/21title\">redirected</a>.</body></html>"], @closed=false>, @header={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "Location"=>"http://test.host/articles/21title", "Set-Cookie"=>"ahoy_visitor=5b32eaaa-e601-4d34-baa2-3995754538db; path=/; expires=Wed, 09 May 2018 07:40:42 -0000\nahoy_visit=daa7dcce-0612-493a-b461-2f1d515eb6ef; path=/; expires=Mon, 09 May 2016 11:40:42 -0000\nahoy_track=true; path=/", "Content-Type"=>"text/html; charset=utf-8"}, @status=301, @sending_file=false, @blank=false, @cv=#<MonitorMixin::ConditionVariable:0x007f8eca5a3830 @monitor=#<ActionController::TestResponse:0x007f8ecf87f590 ...>, @cond=#<Thread::ConditionVariable:0x007f8eca5a3808>>, @committed=false, @sending=false, @sent=false, @content_type=#<Mime::Type:0x007f8ec977fc90 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-405144162176621470>, @charset="utf-8", @cache_control={}, @etag=nil, @request=#<ActionController::TestRequest:0x007f8ecf87fba8 @env={"rack.version"=>[1, 3], "rack.input"=>#<StringIO:0x007f8eca5a0cc0>, "rack.errors"=>#<StringIO:0x007f8ecfad6ed8>, "rack.multithread"=>true, "rack.multiprocess"=>true, "rack.run_once"=>false, "REQUEST_METHOD"=>"GET", "SERVER_NAME"=>"example.org", "SERVER_PORT"=>"80", "QUERY_STRING"=>"", "rack.url_scheme"=>"http", "HTTPS"=>"off", "SCRIPT_NAME"=>nil, "CONTENT_LENGTH"=>"0", "HTTP_HOST"=>"test.host", "REMOTE_ADDR"=>"0.0.0.0", "HTTP_USER_AGENT"=>"Rails Testing", "action_dispatch.routes"=>#<ActionDispatch::Routing::RouteSet:0x007f8ecccc79e8>, "action_dispatch.parameter_filter"=>[:password], "action_dispatch.redirect_filter"=>[], "action_dispatch.secret_token"=>nil, "action_dispatch.secret_key_base"=>"b5686a469d5c83353beeefcbe8daf8ac10295364ce6356d56e0fe98ef421e7bc2bb35cbc603e00d6a40a81d555d8b9b4d15a30fa190e8e418264434b6246f21f", "action_dispatch.show_exceptions"=>false, "action_dispatch.show_detailed_exceptions"=>true, "action_dispatch.logger"=>#<ActiveSupport::Logger:0x007f8eccc660d0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007f8eccc66058 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007f8eccea0760 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007f8eccc65fb8 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/dariusgoore/development/blackops/log/test.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007f8eccc65ef0>>, @local_levels=#<ThreadSafe::Cache:0x007f8eccc65d38 @backend={}, @default_proc=nil>, @thread_hash_level_key=:"ThreadSafeLogger#70125648818280@level">, "action_dispatch.backtrace_cleaner"=>#<Rails::BacktraceCleaner:0x007f8ed3a7d2f8 @filters=[#<Proc:0x007f8ed3a7d1e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:14>, #<Proc:0x007f8ed3a7d1b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:15>, #<Proc:0x007f8ed3a7d190@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:16>, #<Proc:0x007f8ed3a7ce48@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:29>], @silencers=[#<Proc:0x007f8ed3a7ce20@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:19>], @root="/Users/dariusgoore/development/blackops/">, "action_dispatch.key_generator"=>#<ActiveSupport::CachingKeyGenerator:0x007f8ed2461d70 @key_generator=#<ActiveSupport::KeyGenerator:0x007f8ed2461d98 @secret="b5686a469d5c83353beeefcbe8daf8ac10295364ce6356d56e0fe98ef421e7bc2bb35cbc603e00d6a40a81d555d8b9b4d15a30fa190e8e418264434b6246f21f", @iterations=1000>, @cache_keys=#<ThreadSafe::Cache:0x007f8ed2461d48 @backend={"signed_global_ids64"=>"_\xC2X\xD2\x10\x11\x0F\xF4\x97\xC9U\x9E\b\x15Z\x9A\x84\x02Ch\xC4\xBD\xA3\v\x8A:\x05@\xCBp\x91\xF5[\xFD\xDE\x88\xAD\x05 V\xA7\xE4\x82\x9B\xAC\x0E\x11\x90V\xD8\xBD\xF7F\n\xFE\x86Bp\xA7Hu\x8E\xB4\xAC", "signed cookie64"=>"\x12\x10\xD3\x1F\xC7q\x043\xBC\x86\x94%\xEF\xC5kYs\x96\xF14-\xE7\xD4w\xF1\xBF\xF9\"l\xA4\x84\xB6\x1A\xAF\xDDg\x91\xB7}\xB4$\x9A\xC3\xEAH\xED\x17\x94H\xCA'Ob\x0ENt%\x9E\xDC\xB3\xD2\xCA\x11\x8B"}, @default_proc=nil>>, "action_dispatch.http_auth_salt"=>"http authentication", "action_dispatch.signed_cookie_salt"=>"signed cookie", "action_dispatch.encrypted_cookie_salt"=>"encrypted cookie", "action_dispatch.encrypted_signed_cookie_salt"=>"signed encrypted cookie", "action_dispatch.cookies_serializer"=>:json, "action_dispatch.cookies_digest"=>nil, "rack.session"=>{}, "rack.session.options"=>{:key=>"rack.session", :path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :cookie_only=>true, :secure_random=>SecureRandom, :id=>"10b1f0bcd394682baa88eeb8dda727f1"}, "action_controller.instance"=>#<ArticlesController:0x007f8ecf87fe00 @_action_has_layout=true, @_routes=nil, @_headers={"Content-Type"=>"text/html"}, @_status=200, @_request=#<ActionController::TestRequest:0x007f8ecf87fba8 ...>, @_response=#<ActionController::TestResponse:0x007f8ecf87f590 ...>, @_params={"id"=>"1", "controller"=>"articles", "action"=>"show"}, @_url_options={:host=>"test.host", :port=>nil, :protocol=>"http://", :_recall=>{:id=>"1", :controller=>"articles", :action=>"show"}}, @_lookup_context=#<ActionView::LookupContext:0x007f8eca5a3628 @details_key=nil, @details={:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :haml]}, @skip_default_locale=false, @cache=true, @prefixes=["articles", "application"], @rendered_format=nil, @view_paths=#<ActionView::PathSet:0x007f8eca5a3538 @paths=[#<RSpec::Rails::ViewRendering::EmptyTemplateResolver:0x007f8ed38a35e0 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007f8ed38a35b8 @data=#<ActionView::Resolver::Cache::SmallCache:0x007f8ed38a3590 @backend={#<ActionView::LookupContext::DetailsKey:0x007f8ed2f3c650 @hash=1610564969609753123>=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f3c470 @backend={"index"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f3c358 @backend={"articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f3c218 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f3c0b0 @backend={[]=>[app/views/articles/index.html.erb]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>, "articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ada278 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ada188 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ada098 @backend={[]=>[]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>, "application"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3add568 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3add478 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3add388 @backend={[]=>[app/views/layouts/application.html.erb]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3090@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:48 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3068@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:49 (lambda)>>>, @path="/Users/dariusgoore/development/blackops/app/views">, #<RSpec::Rails::ViewRendering::EmptyTemplateResolver:0x007f8ed38a3478 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007f8ed38a3428 @data=#<ActionView::Resolver::Cache::SmallCache:0x007f8ed38a3400 @backend={#<ActionView::LookupContext::DetailsKey:0x007f8ed2f3c650 @hash=1610564969609753123>=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ad8e00 @backend={"articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ad8d38 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ad8c48 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3ad8b58 @backend={[]=>[]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3090@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:48 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3068@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:49 (lambda)>>>, @path="/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/bundler/gems/ckeditor-aeb4581239ba/app/views">, #<RSpec::Rails::ViewRendering::EmptyTemplateResolver:0x007f8ed38a32e8 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007f8ed38a32c0 @data=#<ActionView::Resolver::Cache::SmallCache:0x007f8ed38a3298 @backend={#<ActionView::LookupContext::DetailsKey:0x007f8ed2f3c650 @hash=1610564969609753123>=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f277c8 @backend={"articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f27700 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f27598 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f274a8 @backend={[]=>[]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3090@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:48 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3068@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:49 (lambda)>>>, @path="/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/bundler/gems/mailboxer-d4f0e9c70e29/app/views">, #<RSpec::Rails::ViewRendering::EmptyTemplateResolver:0x007f8ed38a3180 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007f8ed38a3158 @data=#<ActionView::Resolver::Cache::SmallCache:0x007f8ed38a3130 @backend={#<ActionView::LookupContext::DetailsKey:0x007f8ed2f3c650 @hash=1610564969609753123>=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f25bf8 @backend={"articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f25888 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f25748 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f25658 @backend={[]=>[]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3090@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:48 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3068@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:49 (lambda)>>>, @path="/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/rails_admin-0.6.7/app/views">, #<RSpec::Rails::ViewRendering::EmptyTemplateResolver:0x007f8ed38a3018 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007f8ed38a2ff0 @data=#<ActionView::Resolver::Cache::SmallCache:0x007f8ed38a2fc8 @backend={#<ActionView::LookupContext::DetailsKey:0x007f8ed2f3c650 @hash=1610564969609753123>=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f24230 @backend={"articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f24118 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed2f24028 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3adff98 @backend={[]=>[]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3090@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:48 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3068@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:49 (lambda)>>>, @path="/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/kaminari-0.16.3/app/views">, #<RSpec::Rails::ViewRendering::EmptyTemplateResolver:0x007f8ed38a2e88 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007f8ed38a2e60 @data=#<ActionView::Resolver::Cache::SmallCache:0x007f8ed38a2e38 @backend={#<ActionView::LookupContext::DetailsKey:0x007f8ed2f3c650 @hash=1610564969609753123>=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3aded00 @backend={"articles"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3adec38 @backend={"layouts"=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3adeb48 @backend={false=>#<ActionView::Resolver::Cache::SmallCache:0x007f8ed3adea58 @backend={[]=>[]}, @default_proc=nil>}, @default_proc=#<Proc:0x007f8ecc8c30e0@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:46 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c30b8@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:47 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3090@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:48 (lambda)>>}, @default_proc=#<Proc:0x007f8ecc8c3068@/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb:49 (lambda)>>>, @path="/Users/dariusgoore/development/blackops/.bundle/gems/ruby/2.3.0/gems/devise-3.5.6/app/views">]>>, @_env={}, @_config={}, @_action_name="show", @_response_body=["<html><body>You are being <a href=\"http://test.host/articles/21title\">redirected</a>.</body></html>"], @marked_for_same_origin_verification=true, @ahoy=#<Ahoy::Tracker:0x007f8eca590cd0 @store=#<Ahoy::Store:0x007f8eca590c30 @options={:controller=>#<ArticlesController:0x007f8ecf87fe00 ...>, :ahoy=>#<Ahoy::Tracker:0x007f8eca590cd0 ...>}, @controller=#<ArticlesController:0x007f8ecf87fe00 ...>, @request=#<ActionController::TestRequest:0x007f8ecf87fba8 ...>, @bot=false>, @controller=#<ArticlesController:0x007f8ecf87fe00 ...>, @request=#<ActionController::TestRequest:0x007f8ecf87fba8 ...>, @options={:controller=>#<ArticlesController:0x007f8ecf87fe00 ...>}, @existing_visitor_id=nil, @visitor_token="5b32eaaa-e601-4d34-baa2-3995754538db", @visitor_id="5b32eaaa-e601-4d34-baa2-3995754538db", @existing_visit_id=nil, @visit_token="daa7dcce-0612-493a-b461-2f1d515eb6ef", @visit_id="daa7dcce-0612-493a-b461-2f1d515eb6ef">, @current_user=nil, @article=#<Article id: 1, title: "21Title", created_at: "2016-05-09 07:40:42", updated_at: "2016-05-09 07:40:42", user_id: nil, category_id: nil, date: "2016-05-09", state_id: 33, city: "Albany", address: nil, zipcode: nil, longitude: -122.0842499, latitude: 37.4224764, avatar: nil, slug: "21title", video_url: nil, state: nil, age: nil, overview: "A new article", community_action: nil, litigation: nil, country: nil, remove_avatar: nil>, @commentable=#<Article id: 1, title: "21Title", created_at: "2016-05-09 07:40:42", updated_at: "2016-05-09 07:40:42", user_id: nil, category_id: nil, date: "2016-05-09", state_id: 33, city: "Albany", address: nil, zipcode: nil, longitude: -122.0842499, latitude: 37.4224764, avatar: nil, slug: "21title", video_url: nil, state: nil, age: nil, overview: "A new article", community_action: nil, litigation: nil, country: nil, remove_avatar: nil>, @comments=#<ActiveRecord::Associations::CollectionProxy []>, @comment=#<Comment id: nil, content: nil, commentable_id: nil, commentable_type: nil, created_at: nil, updated_at: nil, user_id: nil>, @subjects=#<ActiveRecord::Associations::CollectionProxy [#<Subject id: 1, name: "Luciano O'Hara", age: 1, gender_id: 1, ethnicity_id: 1, unarmed: false, mentally_ill: false, veteran: false, created_at: "2016-05-09 07:40:42", updated_at: "2016-05-09 07:40:42", article_id: 1, homeless: nil>]>>, "warden"=>Warden::Proxy:70125671934040 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x007f8ed2e39cd0>}, "action_dispatch.request.query_parameters"=>{}, "action_dispatch.cookies"=>#<ActionDispatch::Cookies::CookieJar:0x007f8eca5a3df8 @key_generator=#<ActiveSupport::CachingKeyGenerator:0x007f8ed2461d70 @key_generator=#<ActiveSupport::KeyGenerator:0x007f8ed2461d98 @secret="b5686a469d5c83353beeefcbe8daf8ac10295364ce6356d56e0fe98ef421e7bc2bb35cbc603e00d6a40a81d555d8b9b4d15a30fa190e8e418264434b6246f21f", @iterations=1000>, @cache_keys=#<ThreadSafe::Cache:0x007f8ed2461d48 @backend={"signed_global_ids64"=>"_\xC2X\xD2\x10\x11\x0F\xF4\x97\xC9U\x9E\b\x15Z\x9A\x84\x02Ch\xC4\xBD\xA3\v\x8A:\x05@\xCBp\x91\xF5[\xFD\xDE\x88\xAD\x05 V\xA7\xE4\x82\x9B\xAC\x0E\x11\x90V\xD8\xBD\xF7F\n\xFE\x86Bp\xA7Hu\x8E\xB4\xAC", "signed cookie64"=>"\x12\x10\xD3\x1F\xC7q\x043\xBC\x86\x94%\xEF\xC5kYs\x96\xF14-\xE7\xD4w\xF1\xBF\xF9\"l\xA4\x84\xB6\x1A\xAF\xDDg\x91\xB7}\xB4$\x9A\xC3\xEAH\xED\x17\x94H\xCA'Ob\x0ENt%\x9E\xDC\xB3\xD2\xCA\x11\x8B"}, @default_proc=nil>>, @set_cookies={"ahoy_visitor"=>{:value=>"5b32eaaa-e601-4d34-baa2-3995754538db", :expires=>Wed, 09 May 2018 03:40:42 EDT -04:00, :path=>"/"}, "ahoy_visit"=>{:value=>"daa7dcce-0612-493a-b461-2f1d515eb6ef", :expires=>Mon, 09 May 2016 07:40:42 EDT -04:00, :path=>"/"}, "ahoy_track"=>{:value=>true, :path=>"/"}}, @delete_cookies={}, @host="test.host", @secure=false, @options={:signed_cookie_salt=>"signed cookie", :encrypted_cookie_salt=>"encrypted cookie", :encrypted_signed_cookie_salt=>"signed encrypted cookie", :secret_token=>nil, :secret_key_base=>"b5686a469d5c83353beeefcbe8daf8ac10295364ce6356d56e0fe98ef421e7bc2bb35cbc603e00d6a40a81d555d8b9b4d15a30fa190e8e418264434b6246f21f", :upgrade_legacy_signed_cookies=>false, :serializer=>:json, :digest=>nil}, @cookies={"ahoy_visitor"=>"5b32eaaa-e601-4d34-baa2-3995754538db", "ahoy_visit"=>"daa7dcce-0612-493a-b461-2f1d515eb6ef", "ahoy_track"=>true}, @committed=false, @signed=#<ActionDispatch::Cookies::SignedCookieJar:0x007f8ed482cd68 @parent_jar=#<ActionDispatch::Cookies::CookieJar:0x007f8eca5a3df8 ...>, @options={:signed_cookie_salt=>"signed cookie", :encrypted_cookie_salt=>"encrypted cookie", :encrypted_signed_cookie_salt=>"signed encrypted cookie", :secret_token=>nil, :secret_key_base=>"b5686a469d5c83353beeefcbe8daf8ac10295364ce6356d56e0fe98ef421e7bc2bb35cbc603e00d6a40a81d555d8b9b4d15a30fa190e8e418264434b6246f21f", :upgrade_legacy_signed_cookies=>false, :serializer=>:json, :digest=>nil}, @verifier=#<ActiveSupport::MessageVerifier:0x007f8ed482cc50 @secret="\x12\x10\xD3\x1F\xC7q\x043\xBC\x86\x94%\xEF\xC5kYs\x96\xF14-\xE7\xD4w\xF1\xBF\xF9\"l\xA4\x84\xB6\x1A\xAF\xDDg\x91\xB7}\xB4$\x9A\xC3\xEAH\xED\x17\x94H\xCA'Ob\x0ENt%\x9E\xDC\xB3\xD2\xCA\x11\x8B", @digest="SHA1", @serializer=ActiveSupport::MessageEncryptor::NullSerializer>>>, "rack.request.cookie_hash"=>{}, "action_dispatch.request.path_parameters"=>{:id=>"1", :controller=>"articles", :action=>"show"}, "action_dispatch.request.content_type"=>nil, "action_dispatch.request.request_parameters"=>{}, "action_dispatch.request.flash_hash"=>#<ActionDispatch::Flash::FlashHash:0x007f8eca5a0c48 @discard=#<Set: {}>, @flashes={}, @now=nil>, "PATH_INFO"=>"/articles/1", "action_dispatch.request.parameters"=>{"id"=>"1", "controller"=>"articles", "action"=>"show"}, "action_dispatch.request.formats"=>[#<Mime::Type:0x007f8ec977fc90 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-405144162176621470>]}, @filtered_parameters={"id"=>"1", "controller"=>"articles", "action"=>"show"}, @filtered_env=nil, @filtered_path=nil, @protocol="http://", @port=80, @method=nil, @request_method="GET", @remote_ip="0.0.0.0", @original_fullpath=nil, @fullpath="/articles/1", @ip="0.0.0.0", @uuid=nil, @formats=nil, @set_cookies={}, @cookies={}>>.success?` to return true, got false
     # ./spec/controllers/articles_controller_spec.rb:27:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:67:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:66:in `block (2 levels) in <top (required)>'```

**Comment by trystant** [comment]
Is the user logged in when this spec is being run? That looks like a redirect because the user isn't logged in.

**Comment by trystant** [comment]
So this currently is stuck as a result of friendly_ids interfering with rspec. Some investigation is needed in order to solve the problems with `app/controllers/articles_controller.rb`.

**Comment by campgurus** [comment]
just fyi, this is an illustration of the result right now of friendly_id. When an editor changes an article title, friendly_id updates the slug/url to match. However, the old url is no longer valid, resulting in a 404 error for anyone visiting the page (see the view of crawling errors in Google Webmaster:
<img width="1045" alt="screen shot 2016-06-07 at 12 19 20 pm" src="https://cloud.githubusercontent.com/assets/1260659/15865917/9fd24ea8-2caa-11e6-8709-b5b66e45dc59.png">

It is simple to make the old slug continue to work, but the downside is that it creates a duplicate content problem which will hurt our SEO. The final solution will have to incorporate a 301 redirect from the old url to the new one.

**Comment by rlgreen91** [comment]
Do we still need to automatically redirect old URLs to new ones?  Ideally, we would go through every existing case, and for each time the title has been changed, add a new redirect, as well as making these updates automatically in the app.

If we are already making the redirects, how are we doing so?  I feel this may involve a table for redirect URLs...

**Comment by campgurus** [comment]
i think there is some provision for 301 redirects in . the friendy_id gem, so we could fix links for all cases en masse.

**Comment by rlgreen91** [comment]
But we would still need to set up the redirect for each version of each case, wouldn't we?

**Comment by campgurus** [comment]
I think the gem creates these redirects automatically.  The way to do this is discussed at minute 6:00 of this railscast: http://railscasts.com/episodes/314-pretty-urls-with-friendlyid?autoplay=true and involves putting something like this in the articles#show action in the controller:

```      def find_post
        @post = Post.friendly.find params[:id]
        # If an old id or a numeric id was used to find the record, then
        # the request path will not match the post_path, and we should do
        # a 301 redirect that uses the current friendly id.
        if request.path != post_path(@post)
          return redirect_to @post, :status => :moved_permanently
        end
      end```

**Comment by trystant** [comment]
I wonder how the chart looks currently. @campgurus that was a screenshot from Google Analytics, correct?

**Comment by rlgreen91** [comment]
I'd be interested to see the new chart as well, but I think that code snippet above is worth adding on its own.  I'll make an issue.

**Comment by campgurus** [comment]
The chart is from Google webmasters: https://www.google.com/webmasters/tools/crawl-errors?hl=en&authuser=2&siteUrl=https://ebwiki.org/

new chart below.

<img width="1004" alt="screen shot 2017-11-15 at 4 45 35 am" src="https://user-images.githubusercontent.com/1260659/32829586-7c9b3b98-c9c0-11e7-8989-c03c4b96aad3.png">
