### ISSUE TITLE
Failsafe from rollbar-gem. Net::OpenTimeout in /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:930:in `connect': error in process_payload

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#632]
View details in Rollbar: [https://rollbar.com/trystant/BOW/items/486/](https://rollbar.com/trystant/BOW/items/486/)

```
Failsafe from rollbar-gem. Net::OpenTimeout in /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:930:in `connect': error in process_payload
```

**Comment by trystant** [comment]
I believe we can close this.
