### ISSUE TITLE
Validating article for subject causes failing tests

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#73]
FactoryGirl factory does not create the associated subjects at this point. e.g.:

```
Failures:

  1) ArticlesController#index assigns all articles to @articles
     Failure/Error: let(:articles) { FactoryGirl.create_list(:article, 4) }
     ActiveRecord::RecordInvalid:
       Validation failed: Subjects You need to add at least one subject to this case
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block (2 levels) in define_list_strategy_method'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `times'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `each'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `map'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block in define_list_strategy_method'
     # ./spec/controllers/articles_controller_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/controllers/articles_controller_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:73:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:72:in `block (2 levels) in <top (required)>'
```

**Comment by trystant** [comment]
@campgurus Is this still happening, and if so, is this on master or a feature branch?

**Comment by campgurus** [comment]
fixed by @trystant
