### ISSUE TITLE
Failsafe from rollbar-gem. PG::Error: "invalid encoding name: unicode" in /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `set_client_encoding': build_item in exception_data

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#814]
View details in Rollbar: [https://rollbar.com/trystant/BOW/items/623/](https://rollbar.com/trystant/BOW/items/623/)

```
Failsafe from rollbar-gem. PG::Error: "invalid encoding name: unicode" in /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `set_client_encoding': build_item in exception_data
```

**Comment by trystant** [comment]
This looks like a PG driver related error that happens sporadically. Fixing this is outside EBWiki scope.
