### ISSUE TITLE
Failsafe from rollbar-gem. PG::Error: "invalid encoding name: unicode" in /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `set_client_encoding': build_item in exception_data

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#843]
View details in Rollbar: [https://rollbar.com/trystant/BOW/items/653/](https://rollbar.com/trystant/BOW/items/653/)

```
Failsafe from rollbar-gem. PG::Error: "invalid encoding name: unicode" in /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `set_client_encoding': build_item in exception_data
```

**Comment by trystant** [comment]
This can be closed.
